# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certreader < Formula
  desc "Output detailed information about TLS certificates from local files, network hosts or clipboard.
"
  homepage "https://github.com/jonhadfield/certreader"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonhadfield/certreader/releases/download/v0.0.1/certreader_0.0.1_darwin_amd64.tar.gz"
      sha256 "11475cd6c2ec51ee62bd17a082375564aefea71ea896a2c3ea05a92e041d1011"

      def install
        bin.install "certreader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonhadfield/certreader/releases/download/v0.0.1/certreader_0.0.1_darwin_arm64.tar.gz"
      sha256 "01d8e46fef8e1f88a4bc059ce9ebfc6293d53ddd4ab844af6f7321e79171c38a"

      def install
        bin.install "certreader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonhadfield/certreader/releases/download/v0.0.1/certreader_0.0.1_linux_amd64.tar.gz"
      sha256 "2f7a4f65f2106f3069469fe561a7f2fb85ecb696034383893c97810178dff8a6"
      def install
        bin.install "certreader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonhadfield/certreader/releases/download/v0.0.1/certreader_0.0.1_linux_arm64.tar.gz"
      sha256 "38d006d549ae4839707102c6d56a9732d87f35cafee420bc0de72f4a2cf0b20b"
      def install
        bin.install "certreader"
      end
    end
  end
end
