# This file was generated by GoReleaser. DO NOT EDIT.
cask "certreader" do
  version "0.18.2"

  on_macos do
    on_arm do
      sha256 "496585e4d202bd59b049610b8d003f91347849c6d3f9a57dc01721731db0db52"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff43723c62f81097c83c1d1319181928bd4207a541e466c2aa71cea17a630b1f"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certreader"
  desc "Output detailed information about TLS certificates..."
  homepage "https://github.com/jonhadfield/certreader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certreader"

  # No zap stanza required
end
