# This file was generated by GoReleaser. DO NOT EDIT.
cask "certreader" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "b9d405adea9e020e754efddbea187e20cf390c8369abd4eaaabb77ee069f2d2f"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1dc23710e166e999f7c3f4c735855ded4354e3e96a8a94b2e3ac098cae85d86a"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certreader"
  desc "Output detailed information about TLS certificates..."
  homepage "https://github.com/jonhadfield/certreader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certreader"

  # No zap stanza required
end
