# This file was generated by GoReleaser. DO NOT EDIT.
cask "certreader" do
  version "0.19.0"

  on_macos do
    on_arm do
      sha256 "243b1d6f368e44e3d61359c96a375afd5b0436bdc0aa998ccd5a6b74935fc200"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "81fcc7d98348f4aac2b4a91af69d76aa2a403ad85b90e7f8b27eb12277246830"
      url "https://github.com/jonhadfield/certreader/releases/download/v#{version}/certreader_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certreader"
  desc "Output detailed information about TLS certificates..."
  homepage "https://github.com/jonhadfield/certreader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certreader"

  # No zap stanza required
end
